#define STAGE_WIDTH 12
#define STAGE_HEIGHT 22
#define TILE_SIZE 22
#define TETROMINO_SIZE 4
#define LINE_POINTS 100
#define DESCENT_SPEED_INCREASE_THRESHOLD 300
#define MAX_DESCENT_TIME 0.2

#define SCORE_TEXT_X 500
#define SCORE_TEXT_Y 80
#define FONT_SIZE 20
